//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Nhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nhanvien()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int MaNV { get; set; }
        [StringLength(30, ErrorMessage = "Số ký tự tối đa là 30")]
        [Required(ErrorMessage = "Bạn chưa nhập họ nhân viên")]
        public string HoNV { get; set; }
        [StringLength(20, ErrorMessage = "Số ký tự tối đa là 20")]
        [Required(ErrorMessage = "Bạn chưa nhập tên nhân viên")]
        public string Ten { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập địa chỉ")]
        public string Diachi { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập số điện thoại")]
        [Range(0, Int32.MaxValue, ErrorMessage = "Bạn phải nhập số")]
        public string Dienthoai { get; set; }
        [EmailAddress(ErrorMessage = "Email không hợp lệ")]
        [Required(ErrorMessage = "Bạn chưa nhập Email")]
        public string Email { get; set; }
        [MinLength(5, ErrorMessage = "Số ký tự tối thiểu là 5 ký tự")]
        [StringLength(30, ErrorMessage = "Số ký tự tối đa là 30 ký tự")]
        [Required(ErrorMessage = "Bạn chưa nhập mật khẩu")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Bạn chưa chọn quyền cho nhân viên")]
        public bool Admin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
