//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTDHs = new HashSet<CTDH>();
        }
        [Required(ErrorMessage = "Bạn chưa nhập mã sản phẩm")]
        public string MaSP { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập tên sản phẩm")]
        public string TenSP { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập đơn giá sản phẩm")]
        public int DonGia { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập số lượng sản phẩm")]
        public int SoLuong { get; set; }
        [Required(ErrorMessage = "Bạn chưa chọn mã loại sản phẩm")]
        public int MaLoaiSP { get; set; }
        [Required(ErrorMessage = "Bạn chưa chọn hình sản phẩm")]
        public string HinhSP { get; set; }
        public string SLErrorMessage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDH> CTDHs { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
    }
}
